# Generated by Django 2.0.5 on 2018-06-11 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Nombre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ApiaryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('nucs', models.IntegerField(verbose_name='núcleos')),
                ('hives', models.IntegerField(verbose_name='colmenas')),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='apiary.Apiary')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='cantidad')),
                ('date', models.DateField(verbose_name='fecha')),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='apiary.Apiary')),
            ],
        ),
        migrations.AddField(
            model_name='apiary',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='apiary.ApiaryStatus'),
        ),
    ]
