# Generated by Django 2.0.5 on 2018-06-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0003_auto_20180601_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('nucs', models.IntegerField(verbose_name='núcleos')),
                ('hives', models.IntegerField(verbose_name='colmenas')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='cantidad')),
                ('date', models.DateField(verbose_name='fecha')),
            ],
        ),
        migrations.RemoveField(
            model_name='apiary',
            name='hive',
        ),
        migrations.RemoveField(
            model_name='apiary',
            name='nuc',
        ),
        migrations.AddField(
            model_name='harvest',
            name='apiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='apiary.Apiary'),
        ),
        migrations.AddField(
            model_name='apiarystatus',
            name='apiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='apiary.Apiary'),
        ),
    ]
