# Generated by Django 2.0.5 on 2018-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0003_auto_20180613_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarystatus',
            name='date',
            field=models.DateField(null=True, verbose_name='fecha'),
        ),
    ]
