# Generated by Django 2.0.5 on 2018-06-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventaryproduct',
            name='inventary',
        ),
        migrations.RemoveField(
            model_name='inventaryproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='Inventary',
        ),
        migrations.DeleteModel(
            name='InventaryProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
