# Generated by Django 2.0.5 on 2018-07-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180615_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='category examples'),
            preserve_default=False,
        ),
    ]
