# Generated by Django 2.0.5 on 2018-12-27 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0004_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('amount', models.FloatField(verbose_name='cantidad en kg')),
                ('value', models.FloatField(verbose_name='monto facturado')),
                ('description', models.TextField(verbose_name='descripción')),
                ('logged_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-value'],
            },
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date', 'product']},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounting.Category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounting.Product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='value',
            field=models.FloatField(verbose_name='monto pagado'),
        ),
    ]
