# Generated by Django 2.0.5 on 2019-02-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20181227_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depreciationinfo',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='DepreciationInfo',
        ),
    ]
